# Generated by Django 6.0.4 on 2026-04-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
