# Generated by Django 6.0.4 on 2026-04-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0002_alter_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='full_name',
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='city_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
