# Generated by Django 6.0.4 on 2026-04-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0003_remove_personaldetails_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldetails',
            old_name='city_state',
            new_name='cityState',
        ),
        migrations.RenameField(
            model_name='personaldetails',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='personaldetails',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='personaldetails',
            old_name='place_of_birth',
            new_name='placeOfBirth',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='summary',
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='dateOfBirth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='github',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='linkedin',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
