# Generated by Django 6.0.4 on 2026-04-17 11:34

import cv_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0006_alter_education_end_date_alter_education_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='id',
            field=models.CharField(default=cv_api.models.generate_short_id, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.CharField(default=cv_api.models.generate_short_id, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default=cv_api.models.generate_short_id, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='id',
            field=models.CharField(default=cv_api.models.generate_short_id, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reference',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='id',
            field=models.CharField(default=cv_api.models.generate_short_id, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.CharField(default=cv_api.models.generate_short_id, max_length=50, primary_key=True, serialize=False),
        ),
    ]
