# Generated by Django 6.0.4 on 2026-04-17 13:54

import cv_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0009_alter_language_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='id',
            field=models.CharField(default=cv_api.models.generate_short_id, max_length=50, primary_key=True, serialize=False),
        ),
    ]
