# Generated by Django 6.0.4 on 2026-04-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0012_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
