# Generated by Django 6.0.4 on 2026-04-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0013_alter_project_github_link_alter_project_live_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='applestore_link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='playstore_link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
