# Generated by Django 6.0.4 on 2026-04-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0014_project_applestore_link_project_playstore_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
